### ISSUE TITLE
Don't forget to replace your placeholder logo.

### ISSUE THREAD

**Issue by kilakewe** [olinoles/portfolio#2]
https://github.com/olinoles/olinoles.github.io/blob/806c1092af81aa4c5b93624ba78a5125422d9df3/components/Header/index.vue#L8

**Comment by olinoles** [comment]
Thanks, replaced in commit [2d723eb60c86e2555c139c071843208a55691206](https://github.com/olinoles/olinoles.github.io/commit/2d723eb60c86e2555c139c071843208a55691206) :)
